
package MenuVentanas;
import javax.swing.JOptionPane;
import java.io.*;

/**
 * Clase que representa a la ventana de ingresar, la cual valida a los usuarios para poder jugar
 * 
 */
public class Ingresar extends javax.swing.JFrame  {
    String dato, dato2, jugador1, jugador2;
    static String nombre1, nombre2;

    
    public Ingresar() {
        initComponents();
        botonesTransparentes();// se manda a llamar en el constructor para que se ejecute
        this.setLocationRelativeTo(null);//para que este en el centro 
    }
    
    /**
     * Metodo que hace transparentes los botones. 
     */
     public void botonesTransparentes(){
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        
        CrearUS.setOpaque(false);
        CrearUS.setContentAreaFilled(false);
        CrearUS.setBorderPainted(false);
    }
    /**
     * Metodo que busca en el archivo "usuarios" si es que el nombre existe
     * @param usuario Será el nombre del usuario que se quiera buscar en el archivo
     * @return Un dato de tipo String, el cual si es verdadero regresara el nombre. 
     */
    public String buscarUsuario(String usuario){
		String linea;

		try{
			File archivo = new File("usuarios.txt");//se busca en el archivo "usuarios"
			if(archivo.exists()){
				BufferedReader br = new BufferedReader(new FileReader (archivo));
				linea = br.readLine();

				while(linea != null){
                                    //las contraseñas, nombres y puntuaciones estan separadas por ; y cada dato se guatdara en un arreglo
					String[] resultado = linea.split(";");	
					if(resultado[0].equals(usuario)){//se compara si es que esta existe
						dato = resultado[0];
					}
	         		linea=br.readLine();
				}
			}
			else{
                            JOptionPane.showMessageDialog(null,"Aún no hay usuarios existentes");
				
			}
		}catch(IOException e){
			e.printStackTrace();
		}
		return dato;

	}
    
 /**
  * Metodo que busca la contraseña en el archivo "usuarios" para saber si existe
  * @param contra un dato de tipo String el cual es la contraseña que ingresa el usuario 
  * @return Dato de tipo String que contiene la contraseña si es que esta se encuentra en el archivo 
  */
    public String buscarContrasena(String contra){
		String linea;

		try{
			File archivo = new File("usuarios.txt");
			if(archivo.exists()){
				BufferedReader br = new BufferedReader(new FileReader (archivo));
				linea = br.readLine();//se leen todas las lineas de nuestro 

				while(linea != null){
                                    //con split separamos nuestros datos para despues poder ser comparados
					String[] resultado = linea.split(";");	
					if(resultado[1].equals(contra)){//se compara y si son iguales regresa la contraseña
						dato2 = resultado[1];
					}
	         		linea=br.readLine();
				}
			}
			else{
				//Password.setText(null);
				JOptionPane.showMessageDialog(null,"Aún no hay usuarios existentes");
			}
		}catch(IOException e){
			e.printStackTrace();
		}
		return dato2;

	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        Usuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CrearUS = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Usuario2 = new javax.swing.JTextField();
        Password2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel2.setText("Usuario 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 40));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        Password.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 240, 30));

        Usuario.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 240, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/ingresar.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 100, 40));

        CrearUS.setBackground(new java.awt.Color(255, 255, 255));
        CrearUS.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        CrearUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/CrearU.png"))); // NOI18N
        CrearUS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearUSMouseClicked(evt);
            }
        });
        getContentPane().add(CrearUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 130, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/salirs.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 80, 40));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel6.setText("Usuario 2:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 140, 40));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel5.setText("Contraseña :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, 20));

        Usuario2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Usuario2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 240, 30));

        Password2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password2ActionPerformed(evt);
            }
        });
        getContentPane().add(Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 240, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pong registro.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
       //si es que el usuario se le ha olvidado crear uno nuevo podra regresar a la ventana 
    private void CrearUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUSMouseClicked
        CrearUsuario usuario= new CrearUsuario();//instanciamos la ventana de CrearUsuario
        usuario.setVisible(true);//se muesta esa ventana
        this.setVisible(false);// se ocula la ventana actual
    }//GEN-LAST:event_CrearUSMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       System.exit(0);//se hace este para poder quitar la decoracion de la ventana por defecto 
    }//GEN-LAST:event_jButton2MouseClicked
    /**
     * Metodo que ingresa a la siguiente ventana si es que se han ingresado correctamente los usuarios 
     * @param evt 
     */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        if(Usuario.getText().equals("")){//se compara si es que no se ha escrito nada
			JOptionPane.showMessageDialog(null,"Usuario 1 por favor escribe tu nombre de usuario");			
	}
        else if(Password.getText().equals("")){ 
            JOptionPane.showMessageDialog(null,"Escribe tu contraseña Usuario 1");       
        }
        else if(!Usuario.getText().equals(buscarUsuario(Usuario.getText()))){//si es que no se encuentra el usuario se manda una advertencia
            Usuario.setText(null);
            JOptionPane.showMessageDialog(null,"TU NOMBRE DE USUARIO ES INCORRECTO USUARIO 1");
	}
	else if(!Password.getText().equals(buscarContrasena(Password.getText()))){//si es que la contraseña no se encuentra manda una advertencia
            Password.setText("");
            JOptionPane.showMessageDialog(null,"TU CONTRASEÑA ES INCORRECTA USUARIO 1");
	}
        else if(Usuario2.getText().equals("")){
			JOptionPane.showMessageDialog(null,"Usuario 2 por favor escribe tu usuario");		
	}
        else if(Password2.getText().equals("")){ 
            JOptionPane.showMessageDialog(null,"Escribe tu contraseña usuario 2");       
        }
        else if(!Usuario2.getText().equals(buscarUsuario(Usuario2.getText()))){
            Usuario2.setText(null);
            JOptionPane.showMessageDialog(null,"TU NOMBRE DE USUARIO ES INCORRECTO USUARIO 2");
	}
	else if(!Password2.getText().equals(buscarContrasena(Password2.getText()))){
            Password2.setText(null);
            JOptionPane.showMessageDialog(null,"TU CONTRASEÑA ES INCORRECTA USUARIO 2");
	}
        else if(Usuario.getText().equals(Usuario2.getText())){//solo se podra ingresar con dos usuarios diferentes
            JOptionPane.showMessageDialog(null,"NO SE PUEDE USAR EL MISMO USUARIO");

        }
        else if(Usuario.getText().equals(buscarUsuario(Usuario.getText())) && Password.getText().equals(buscarContrasena(Password.getText())) && Usuario2.getText().equals(buscarUsuario(Usuario2.getText())) && Password2.getText().equals(buscarContrasena(Password2.getText()))){//Comparamos si el nombre de ambos usuarios y sus contraseñas sean correctas
            Instrucciones inst=new Instrucciones();//instanciamos la siguente ventana
            nombre1 = Usuario.getText();
            nombre2 = Usuario2.getText();
            inst.setVisible(true);//se muestra la siguente ventana
            this.setVisible(false);//se oculta esta ventana
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void Password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearUS;
    private javax.swing.JPasswordField Password;
    private javax.swing.JPasswordField Password2;
    private javax.swing.JTextField Usuario;
    private javax.swing.JTextField Usuario2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
//Los Getters los usaremos a la hora de mostrar el usuario ganador 
    public String getUsuario() {
        return nombre1;
    }

    public String getUsuario2() {
        return nombre2;
    }
}
