
package MenuVentanas;

import pong.Ejecucion;
import pong.VentanaPong;

/**
 *Clase que representa una ventana, la cual muestra las inatrucciones para jugar
 * 
 */
public class Instrucciones extends javax.swing.JFrame {
    
     /*
     * Se van a crear objetos asi como también las instancias de éstas para 
     * poder utilizarlas en la generación y ejecución de los diferentes 
     * controles que se desarrollan en el diseño de la ventana
     */
    VentanaPong pong = new VentanaPong();
    Ejecucion ejecucion = new Ejecucion(pong);
    Ingresar ingresar = new Ingresar();
     
    /**
     * Para Instrucciones se inicializa y se hace referencia a la licalización
     * de la ventana que aparezca, con el objetivo de que se coloque en el centro.
     */
    public Instrucciones() {
        initComponents();
        botonesTransparentes();
        this.setLocationRelativeTo(null);//para que este en el centro 
    }
    
    /**
     * El metodo botonesTransparentes se encarga de 
     * transparentar los botones presentados en el menu.
     */
    public void botonesTransparentes(){
     
        Iniciar.setOpaque(false);//Hacemos que  no se dibujen los pixeles del boton
        Iniciar.setContentAreaFilled(false);//Opcion principal para tener un boton transparente
        Iniciar.setBorderPainted(false);//No dibujamos el borde
        
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Iniciar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/INICIAR.png"))); // NOI18N
        Iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarMouseClicked(evt);
            }
        });
        getContentPane().add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 140, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/salirs.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ins (2).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    /**
     * Se crea una instancia de la VentanaPong con el objetivo de hacerla visible al momento
     * de pasar de la ventana anterior a esta de Instrucciones y que para al momento en que 
     * continuemos con la ejecución del programa se cierre dando paso a la iniciación del
     * juego PONG, que se encuentra señalado en la linea 171 al "iniciar" con start la clase
     * Ejecución
     */
    private void IniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarMouseClicked
       
        VentanaPong pong = new VentanaPong();        
        String jugador1;
        jugador1 = ingresar.getUsuario();
        //pong.setVisible(true);
        this.setVisible(false);
        ejecucion.start();
    }//GEN-LAST:event_IniciarMouseClicked

    /**
     * Este es el boton que hace referencia a la salida de la ventana, poniendo fin a lo que se llevaba de
     * avance en el juego, ya que cierra por completo todos los archivos, ventanas, hilos, que se estaban
     * ejecutando
     */
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instrucciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
